# <span style="color:green"><ins>Chapitre 2: Vecteurs, matrices et systèmes linéaires</ins></span>

In [1]:
import numpy as np

Dans ce chapitre, nous allons présenter quelques fonctions de la sous-librairie "linalg" de numpy (linear algebra). La liste exhaustive de toutes les fonctions disponibles est présentée sous le lien suivant :
https://numpy.org/doc/stable/reference/routines.linalg.html

## Matrices et vecteurs : syntaxe

On supposera toujours que les matrices et vecteurs sont définis comme des tableaux numpy comme suit :<br/>
Pour définir
\begin{equation*}
A=
\left(
\begin{matrix}
1 & 2\\
3 & 4
\end{matrix}
\right)
\end{equation*}
On code :

In [2]:
A=np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


Pour définir
\begin{equation*}
A=
\left(
\begin{matrix}
1\\
2
\end{matrix}
\right)
\end{equation*}
On code :

In [3]:
A=np.array([[1],[2]])
print(A)

[[1]
 [2]]


Pour définir
\begin{equation*}
A=
\left(
\begin{matrix}
1 & 2
\end{matrix}
\right)
\end{equation*}
On code :

In [4]:
A=np.array([[1,2]])
print(A)

[[1 2]]


## Opérations matricielles versus opérations terme à terme

### La règle

Lorsqu'on écrit `A@B`, c'est une multiplication matricielle, les dimensions de $A$ et $B$ doivent donc satisfaire les propriétés matricielles.<br/>
Lorsqu'on écrit `A*B`, `A/B` ou `A**B`, ce sont des opérations terme à terme (l'opérateur s'applique entre les mêmes composantes de $A$ et $B$). $A$ et $B$ doivent donc avoir la même dimension.

### Exemple 1

Soient les matrices suivantes :

In [5]:
A=np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [6]:
B=np.array([[5,0],[2,1]])
print(B)

[[5 0]
 [2 1]]


`A@B` va donner la multiplication matricielle, et `A*B` va donner la multiplication terme à terme (élément (i,j) de $A$ multiplié par l'élément (i,j) de $B$) :

In [7]:
print(A@B)

[[ 9  2]
 [23  4]]


In [8]:
print(A*B)

[[5 0]
 [6 4]]


### Exemple 2

Soient les matrices suivantes :

In [9]:
A=np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [10]:
B=np.array([[5],[2],[0]])
print(B)

[[5]
 [2]
 [0]]


`A@B` va donner la multiplication matricielle, et `A*B` va donner **une erreur** car  $A$ et $B$ ne sont pas de même dimension :

In [11]:
print(A@B)

[[ 9]
 [30]]


In [12]:
print(A*B)

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

### Exemple 3

Soient les matrices suivantes :

In [13]:
A=np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [14]:
B=np.array([[5,0,3],[2,1,5]])
print(B)

[[5 0 3]
 [2 1 5]]


`A@B` va donner **une erreur** car le nombre de colonnes de $A$ n'est pas égal au nombre de lignes de $B$, et `A*B` va donner la multiplication terme à terme :

In [15]:
print(A@B)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [16]:
print(A*B)

[[ 5  0  9]
 [ 8  5 30]]


### Exemple 4

Soit la matrice suivante :

In [17]:
A=np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


L'opération `2*A` multiplie chaque élément de $A$ par 2 :

In [18]:
print(2*A)

[[ 2  4  6]
 [ 8 10 12]]


Tandis que `2@A` renverra une erreur car $2$ et $A$ ne sont pas de même dimension :

In [19]:
print(2@A)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

### Exemple 5

Soit la matrice suivante :

In [20]:
A=np.array([[1,2],[4,5]])
print(A)

[[1 2]
 [4 5]]


Faire `A**2` signifie `A*A`, c'est à dire que tous les termes de la matrice sont élevés au carré. Code :

In [21]:
print(A**2)

Si maintenant on veut prendre le carré au point de vue matriciel, qui signifie `A@A`, la syntaxe est la suivante :

In [22]:
print(np.linalg.matrix_power(A,2))

[[ 9 12]
 [24 33]]


## Exercice 1

<ol>
    <li>Construisez la matrice $A$ donnée par 
\begin{equation}
A=v^{t}.v
\end{equation}
    où $v=(0.5,1,1.5,2,2.5,3,3.5,4,4.5,5)$ et $v^{t}$ est la transposée de $v$.</li>
    <li>Construisez le vecteur $u$ défini par
\begin{equation}
u=w.A^3+4.v
\end{equation}
    où $w$ est un vecteur de même taille que $v$ dont les composantes sont le carré des composantes correspondantes de $v$.</li>
    <li>Remplacez la troisième composante de $u$ par le nombre $7$.</li>
</ol>

In [23]:
v=np.array([[0.5,1,1.5,2,2.5,3,3.5,4,4.5,5]])
print(v)
print(v.shape)
vt=np.transpose(v)
print(vt)
print(vt.shape)
A=vt@v              # produit matriciel
print(A)
print(A.shape)

[[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]]
(1, 10)
[[0.5]
 [1. ]
 [1.5]
 [2. ]
 [2.5]
 [3. ]
 [3.5]
 [4. ]
 [4.5]
 [5. ]]
(10, 1)
[[ 0.25  0.5   0.75  1.    1.25  1.5   1.75  2.    2.25  2.5 ]
 [ 0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.  ]
 [ 0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5 ]
 [ 1.    2.    3.    4.    5.    6.    7.    8.    9.   10.  ]
 [ 1.25  2.5   3.75  5.    6.25  7.5   8.75 10.   11.25 12.5 ]
 [ 1.5   3.    4.5   6.    7.5   9.   10.5  12.   13.5  15.  ]
 [ 1.75  3.5   5.25  7.    8.75 10.5  12.25 14.   15.75 17.5 ]
 [ 2.    4.    6.    8.   10.   12.   14.   16.   18.   20.  ]
 [ 2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5 ]
 [ 2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5  25.  ]]
(10, 10)


In [24]:
w=v**2        # chaque composante au carré
print(w)
u=w@np.linalg.matrix_power(A,3)+4*v            # np.linalg.matrix_power(A,3) signifie A@A@A
print(u)

[[ 0.25  1.    2.25  4.    6.25  9.   12.25 16.   20.25 25.  ]]
[[ 1751488.81640625  3502977.6328125   5254466.44921875  7005955.265625
   8757444.08203125 10508932.8984375  12260421.71484375 14011910.53125
  15763399.34765625 17514888.1640625 ]]


In [25]:
u[0,2]=7
print(u)

[[1.75148882e+06 3.50297763e+06 7.00000000e+00 7.00595527e+06
  8.75744408e+06 1.05089329e+07 1.22604217e+07 1.40119105e+07
  1.57633993e+07 1.75148882e+07]]


## Exercice 2

<ol>
    <li> Construire la matrice $A\in\mathbb{R}^{6\times 6}$ définie par
\begin{equation}
A=Id+u^{t}.u/4
\end{equation}
où $u=(1,2,3,4,5,6)$.</li>
    <li> Ajoutez $2$ à l'élément $A_{23}$.</li>
    <li> Vérifiez que la nouvelle matrice A est une matrice inversible.</li>
    <li> Calculez $A^{-1}$ et vérifiez que le produit $A^{-1}A$ donne l'identité.</li>
</ol>

In [26]:
u=np.array([[1,2,3,4,5,6]])
I=np.identity(6)                   # matrice identité
print(I)
A=I+np.transpose(u)@u/4
print(A)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[ 1.25  0.5   0.75  1.    1.25  1.5 ]
 [ 0.5   2.    1.5   2.    2.5   3.  ]
 [ 0.75  1.5   3.25  3.    3.75  4.5 ]
 [ 1.    2.    3.    5.    5.    6.  ]
 [ 1.25  2.5   3.75  5.    7.25  7.5 ]
 [ 1.5   3.    4.5   6.    7.5  10.  ]]


In [27]:
A[1,2]+=2
print(A)

[[ 1.25  0.5   0.75  1.    1.25  1.5 ]
 [ 0.5   2.    3.5   2.    2.5   3.  ]
 [ 0.75  1.5   3.25  3.    3.75  4.5 ]
 [ 1.    2.    3.    5.    5.    6.  ]
 [ 1.25  2.5   3.75  5.    7.25  7.5 ]
 [ 1.5   3.    4.5   6.    7.5  10.  ]]


In [28]:
print(np.linalg.det(A))   # Déterminant de A - Une matrice est inversible ssi son déterminant est non nul

20.750000000000004


In [29]:
Ainv=np.linalg.inv(A)        # matrice inverse
print(A@Ainv)

[[ 1.00000000e+00 -1.38777878e-16  4.44089210e-16  5.55111512e-16
  -1.11022302e-16 -2.22044605e-16]
 [ 5.55111512e-17  1.00000000e+00 -4.44089210e-16  0.00000000e+00
   0.00000000e+00  2.22044605e-16]
 [ 1.11022302e-16  0.00000000e+00  1.00000000e+00  2.22044605e-16
  -4.44089210e-16  0.00000000e+00]
 [ 1.11022302e-16 -1.11022302e-16  0.00000000e+00  1.00000000e+00
  -4.44089210e-16  0.00000000e+00]
 [ 2.22044605e-16  0.00000000e+00  0.00000000e+00  4.44089210e-16
   1.00000000e+00  2.22044605e-16]
 [ 0.00000000e+00 -1.66533454e-16  0.00000000e+00  2.22044605e-16
  -5.55111512e-16  1.00000000e+00]]


## Exercice 3

Astérix, Spirou, Kid Paddle et Gaston Lagaffe se rendent dans un Kebab. Astérix prend 8 assiettes gyros spéciales, 10 frites et 6 boissons. Il paie 43 euros. Spirou mange 2 frites et 2 boissons, mais ne prend pas d’assiette gyros spéciale, et il paie 9 euros. Kid Paddle se contente d’une assiette gyros spéciale et d’une boisson et paie 4.5 euros. Gaston Lagaffe voudrait prendre 1 assiette gyros spéciale avec 1 frite. Combien devra-t-il payer?

In [30]:
A=np.array([[8,10,6],[0,2,2],[1,0,1]])
print(A)
b=np.array([[43],[9],[4.5]])     # ou bien np.transpose(np.array([[43,9,4.5]]))
print(b)

[[ 8 10  6]
 [ 0  2  2]
 [ 1  0  1]]
[[43. ]
 [ 9. ]
 [ 4.5]]


In [31]:
x=np.linalg.solve(A,b)      # résolution de Ax=b
print(x)
print(x.shape)

[[1.33333333]
 [1.33333333]
 [3.16666667]]
(3, 1)


In [32]:
print("Gaston payera "+str(x[0,0]+x[1,0])+" euros")
# Plus rigoureusement : 
# print("Gaston payera "+str((np.array([[1,1,0]])@x)[0,0])+" euros")    # On multiplie le vecteur des quantités par le vecteur des prix

Gaston payera 2.6666666666666665 euros


In [33]:
# Spécifier le format pour rendre + présentable (.2f signifie arrondi à 2 décimales)
print("Gaston payera "+str("{:.2f}".format(x[0,0]+x[1,0]))+" euros")

Gaston payera 2.67 euros


## Exercice 4

On considère l'équation de récurrence $f(n+1)=3f(n)-2f(n-1)$.
<ol>
<li>(Sur papier) Trouvez une matrice $A$ telle que 
\begin{equation}
    \left(
\begin{matrix}
f(n+1)\\
f(n)
\end{matrix}
\right)
=
A\left(
\begin{matrix}
f(n)\\
f(n-1)
\end{matrix}
\right) 
\end{equation}
</li>
<li>(Sur papier) En déduire l'expression matricielle de $\left(
\begin{matrix}
f(n+1)\\
f(n)
\end{matrix}
\right)$ en fonction de $\left(
\begin{matrix}
f(1)\\
f(0)
\end{matrix}
\right)$
</li>
<li>(Sur Python) En supposant que $f(0)=0$ et $f(1)=1$, calculez $f(14)$ via la relation matricielle.</li>
</ol>

In [34]:
A=np.array([[3,-2],[1,0]])
x=np.linalg.matrix_power(A,13)@np.array([[1],[0]])
print("f(14) = "+str(x[0,0]))

f(14) = 16383


## Exercice 5

Soit la suite 
\begin{eqnarray*}
x_{n+1}=-x_{n}+4x_{n-1}+4x_{n-2}\qquad n\in\{2,3,4,...\}
\end{eqnarray*}
avec les conditions initiales
\begin{eqnarray*}
x_0=1\quad x_1=0\quad x_2=0
\end{eqnarray*}
<ol>
    <li>Ecrire cette équation sous forme matricielle en fonction des conditions initiales.</li>
    <li>En déduire la valeur de $x_{10}$ via Python. 
</ol>

In [5]:
A=np.array([[-1,4,4],[1,0,0],[0,1,0]])
x=np.linalg.matrix_power(A,9)@np.array([[0],[0],[1]])
print("x_10 = "+str(x[1,0]))

x_10 = -340


## Exercice 6

Chaque année, la population d'un pays fait son choix entre deux partis politiques : le parti A et le parti B. On constate les faits suivants:
- $1/3$ des anciens partisans de A sont mécontents et passent au parti B. Les autres anciens de A restent en A. 
- $1/4$ des anciens partisans de B restent en B et les autres passent en A.

<ol>
<li>(Sur papier) Exprimez par un système d'équations le mouvement politique de la population en 1 an.</li>
<li>(Sur papier) Exprimez ce transfert sous forme matricielle.</li>
<li>(Sur Python) Si en 1978 il y a 36000 partisans de A et 900 partisans de B, quelle sera la répartition en l'an 2000? </li>
</ol>

In [36]:
A=np.array([[2/3,3/4],[1/3,1/4]])
x=np.linalg.matrix_power(A,22)@np.array([[36000],[900]])
print("En 2000, il y aura "+str(round(x[0,0]))+" partisans de A et "+str(round(x[1,0]))+" partisans de B.")

En 2000, il y aura 25546 partisans de A et 11354 partisans de B.


## Nota bene

Les exercices 4, 5 et 6 peuvent également être résolus par itérations, à l'aide de boucles `for` ou `while` : voir chapitre 4. 